name: daily_revision_book
description: A daily vocabulary revision app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  pdf: ^3.11.0
  printing: ^5.12.0
  flutter_quill: 8.0.0

# YEH NAYA OVERRIDE ERROR KO HAMESHA KE LIYE FIX KAREGA
dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
